[build]
  publish = "public"
  command = "npm ci --omit=dev"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "ws"]

[build.environment]
  NODE_VERSION = "20"
