[build]
  publish = "public"
  command = "npm ci --omit=dev"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["node_modules/**"]

[build.environment]
  NODE_VERSION = "20"
